### ISSUE TITLE
pytest-assume not compatible with pytest 4.1.0

### ISSUE THREAD

**Issue by tonymackinnon** [astraw38/pytest-assume#8]
We picked this up in our nightly build:

```
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-4.1.0, py-1.7.0, pluggy-0.8.0 -- /home/jenkins/workspace/bmll2_master-TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/bin/python3
cachedir: .pytest_cache
Using --randomly-seed=1546835968
rootdir: /home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q, inifile: setup.cfg
plugins: randomly-1.2.3, profiling-1.3.0, mock-1.10.0, cov-2.6.1, assume-1.2

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/_pytest/main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/_pytest/main.py", line 242, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/_pytest/main.py", line 252, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/_pytest/main.py", line 466, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/pluggy/manager.py", line 250, in check_pending
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace' in plugin <module 'pytest_assume.plugin' from '/home/jenkins/workspace/TDGIKGCWQBI7SLHQKIR24IZTWYAVLOQKKGKZNTPMABCEGCEG6F3Q/.venv/py3.6.6/lib/python3.6/site-packages/pytest_assume/plugin.py'>
```

This error isn't raised with pytest 4.0.2.

**Comment by astraw38** [comment]
Hi, can you update to 1.2.1? I believe I fixed that in pull request #7.

**Comment by astraw38** [comment]
Tested & published!

**Comment by tonymackinnon** [comment]
hmmm, I don't see 1.2.1 on pypi?

https://pypi.org/project/pytest-assume/#history

**Comment by astraw38** [comment]
Done!

**Comment by tonymackinnon** [comment]
Thanks!
